//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.DataTransfer.ConsoleHost {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.DataTransfer.ConsoleHost.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical error: .
        /// </summary>
        internal static string CriticalFailurePrefix {
            get {
                return ResourceManager.GetString("CriticalFailurePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data adapter configuration of type &apos;{0}&apos; can not be created because there is no factory exists that can instantiate it..
        /// </summary>
        internal static string DataAdapterConfigurationFactoryNotFoundFormat {
            get {
                return ResourceManager.GetString("DataAdapterConfigurationFactoryNotFoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}.{2}: {3}.
        /// </summary>
        internal static string HelpAdapterConfigurationOptionFormat {
            get {
                return ResourceManager.GetString("HelpAdapterConfigurationOptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options:.
        /// </summary>
        internal static string HelpConfigurationHeader {
            get {
                return ResourceManager.GetString("HelpConfigurationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get configuration: {0}.
        /// </summary>
        internal static string HelpConfigurationNotAvailableFormat {
            get {
                return ResourceManager.GetString("HelpConfigurationNotAvailableFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}: {2}.
        /// </summary>
        internal static string HelpConfigurationOptionFormat {
            get {
                return ResourceManager.GetString("HelpConfigurationOptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocumentDB Data Migration Tool v{0}.
        /// </summary>
        internal static string HelpHeaderFormat {
            get {
                return ResourceManager.GetString("HelpHeaderFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {2}: {3}.
        /// </summary>
        internal static string HelpKnownAdapterFormat {
            get {
                return ResourceManager.GetString("HelpKnownAdapterFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available sources:.
        /// </summary>
        internal static string HelpKnownSourcesHeader {
            get {
                return ResourceManager.GetString("HelpKnownSourcesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available targets:.
        /// </summary>
        internal static string HelpKnownTargetsHeader {
            get {
                return ResourceManager.GetString("HelpKnownTargetsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dt.exe [{0}&lt;option&gt;:&lt;value&gt;] {0}{1}:&lt;source-name&gt; [{0}{1}.&lt;source-option&gt;:&lt;value&gt;] {0}{2}:&lt;target-name&gt; [{0}{2}.&lt;target-option&gt;:&lt;value&gt;].
        /// </summary>
        internal static string HelpUsageExample {
            get {
                return ResourceManager.GetString("HelpUsageExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage:.
        /// </summary>
        internal static string HelpUsageExampleHeader {
            get {
                return ResourceManager.GetString("HelpUsageExampleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source adapter should be specified.
        /// </summary>
        internal static string SourceNotSpecified {
            get {
                return ResourceManager.GetString("SourceNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}.
        /// </summary>
        internal static string StatisticsFailureItemFormat {
            get {
                return ResourceManager.GetString("StatisticsFailureItemFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failures:.
        /// </summary>
        internal static string StatisticsFailuresHeader {
            get {
                return ResourceManager.GetString("StatisticsFailuresHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferred: {0}; Failed: {1}; Elapsed Time: {2}.
        /// </summary>
        internal static string StatisticsProgressFormat {
            get {
                return ResourceManager.GetString("StatisticsProgressFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferred: {0}
        ///Failed: {1}
        ///Time spent: {2}.
        /// </summary>
        internal static string StatisticsResultFormat {
            get {
                return ResourceManager.GetString("StatisticsResultFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target adapter should be specified.
        /// </summary>
        internal static string TargetNotSpecified {
            get {
                return ResourceManager.GetString("TargetNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source with the name &apos;{0}&apos; is not known.
        /// </summary>
        internal static string UnknownSourceFormat {
            get {
                return ResourceManager.GetString("UnknownSourceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target with the name &apos;{0}&apos; is not known.
        /// </summary>
        internal static string UnknownTargetFormat {
            get {
                return ResourceManager.GetString("UnknownTargetFormat", resourceCulture);
            }
        }
    }
}
