//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.DataTransfer.WpfHost.Basics {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.DataTransfer.WpfHost.Basics.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blobs://&lt;account-key&gt;@&lt;account-name&gt;.blob.core.windows.net/&lt;container&gt;/&lt;blob-regex&gt;.
        /// </summary>
        internal static string BlobUrlSample {
            get {
                return ResourceManager.GetString("BlobUrlSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string DefaultFalseValue {
            get {
                return ResourceManager.GetString("DefaultFalseValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string DefaultTrueValue {
            get {
                return ResourceManager.GetString("DefaultTrueValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select folder:.
        /// </summary>
        internal static string FolderBrowserDescription {
            get {
                return ResourceManager.GetString("FolderBrowserDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert value from type &quot;{0}&quot;, expected type is &quot;{1}&quot;.
        /// </summary>
        internal static string InvalidSourceConvertionType {
            get {
                return ResourceManager.GetString("InvalidSourceConvertionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid storage container URL should be provided.
        /// </summary>
        internal static string InvalidStorageContainerUrl {
            get {
                return ResourceManager.GetString("InvalidStorageContainerUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert value to type &quot;{0}&quot;, expected type is &quot;{1}&quot;.
        /// </summary>
        internal static string InvalidTargetConvertionType {
            get {
                return ResourceManager.GetString("InvalidTargetConvertionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more items should be added.
        /// </summary>
        internal static string NonEmptyCollectionRequired {
            get {
                return ResourceManager.GetString("NonEmptyCollectionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-empty value should be provided.
        /// </summary>
        internal static string NonEmptyStringRequired {
            get {
                return ResourceManager.GetString("NonEmptyStringRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-negative value should be provided.
        /// </summary>
        internal static string NonNegativeNumberRequired {
            get {
                return ResourceManager.GetString("NonNegativeNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value should be greater than zero.
        /// </summary>
        internal static string PositiveNumberRequired {
            get {
                return ResourceManager.GetString("PositiveNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current content of the field will be replaced.
        ///
        ///Do you want to continue?.
        /// </summary>
        internal static string ReplaceContentConfirmation {
            get {
                return ResourceManager.GetString("ReplaceContentConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace Content.
        /// </summary>
        internal static string ReplaceContentConfirmationTitle {
            get {
                return ResourceManager.GetString("ReplaceContentConfirmationTitle", resourceCulture);
            }
        }
    }
}
