//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.DataTransfer.TestsCommon {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.DataTransfer.TestsCommon.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual field value is not a data item, when expected is.
        /// </summary>
        internal static string InvalidDataItemFieldValue {
            get {
                return ResourceManager.GetString("InvalidDataItemFieldValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field names in the actual data item are different.
        /// </summary>
        internal static string InvalidFieldNames {
            get {
                return ResourceManager.GetString("InvalidFieldNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual field value is not the same as expected.
        /// </summary>
        internal static string InvalidFieldValue {
            get {
                return ResourceManager.GetString("InvalidFieldValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of items in the collection field does not match.
        /// </summary>
        internal static string InvalidNumberOfItems {
            get {
                return ResourceManager.GetString("InvalidNumberOfItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual field names collection is null.
        /// </summary>
        internal static string NullActualFieldNames {
            get {
                return ResourceManager.GetString("NullActualFieldNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected field names collection is null.
        /// </summary>
        internal static string NullExpectedFieldNames {
            get {
                return ResourceManager.GetString("NullExpectedFieldNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test settings file does not exist, make sure right test settings file is selected.
        /// </summary>
        internal static string TestSettingsFileMissingFormat {
            get {
                return ResourceManager.GetString("TestSettingsFileMissingFormat", resourceCulture);
            }
        }
    }
}
