//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.DataTransfer.Sql.FunctionalTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.DataTransfer.Sql.FunctionalTests.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data adapter should fail when both Query and QueryFile are set.
        /// </summary>
        internal static string AmbiguousQueryDidNotFail {
            get {
                return ResourceManager.GetString("AmbiguousQueryDidNotFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE {0}
        ///(
        ///{1}
        ///).
        /// </summary>
        internal static string CreateTableCommandFormat {
            get {
                return ResourceManager.GetString("CreateTableCommandFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF OBJECT_ID(&apos;{0}&apos;, &apos;U&apos;) IS NOT NULL
        ///  DROP TABLE {0}.
        /// </summary>
        internal static string DropTableCommandFormat {
            get {
                return ResourceManager.GetString("DropTableCommandFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO {0} ({1}) VALUES ({2}).
        /// </summary>
        internal static string InsertRowsCommandFormat {
            get {
                return ResourceManager.GetString("InsertRowsCommandFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property&quot;{0}&quot; has invalid value.
        /// </summary>
        internal static string InvalidPropertyValueFormat {
            get {
                return ResourceManager.GetString("InvalidPropertyValueFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More data items expected.
        /// </summary>
        internal static string MoreDataItemsExpected {
            get {
                return ResourceManager.GetString("MoreDataItemsExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT {0}.IntColumn, {0}.NVarCharMaxColumn, {1}.IntColumn AS [Nested.IntColumn], {1}.NVarCharMaxColumn AS [Nested.NVarCharMaxColumn], {2}.IntColumn AS [AnotherNested.IntColumn], {2}.NVarCharMaxColumn AS [AnotherNested.NVarCharMaxColumn] 
        ///FROM {0}
        ///INNER JOIN {1} ON {1}.IntColumn = {0}.IntColumn
        ///INNER JOIN {2} ON {2}.IntColumn = {0}.IntColumn.
        /// </summary>
        internal static string OneLevelNestedSelectQueryFormat {
            get {
                return ResourceManager.GetString("OneLevelNestedSelectQueryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &quot;{0}&quot; is missing.
        /// </summary>
        internal static string PropertyMissingFormat {
            get {
                return ResourceManager.GetString("PropertyMissingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM {0}.
        /// </summary>
        internal static string SimpleSelectQueryFormat {
            get {
                return ResourceManager.GetString("SimpleSelectQueryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT {0}.IntColumn, {0}.NVarCharMaxColumn, {1}.IntColumn AS [FirstNested.IntColumn], {1}.NVarCharMaxColumn AS [FirstNested.NVarCharMaxColumn], {2}.IntColumn AS [FirstNested.SecondNested.IntColumn], {2}.NVarCharMaxColumn AS [FirstNested.SecondNested.NVarCharMaxColumn] 
        ///FROM {0}
        ///INNER JOIN {1} ON {1}.IntColumn = {0}.IntColumn
        ///INNER JOIN {2} ON {2}.IntColumn = {1}.IntColumn.
        /// </summary>
        internal static string TwoLevelNestedSelectQueryFormat {
            get {
                return ResourceManager.GetString("TwoLevelNestedSelectQueryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected data item was read.
        /// </summary>
        internal static string UnexpectedDataItem {
            get {
                return ResourceManager.GetString("UnexpectedDataItem", resourceCulture);
            }
        }
    }
}
