//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.DataTransfer.AzureTable.Wpf {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.DataTransfer.AzureTable.Wpf.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary only.
        /// </summary>
        internal static string AzureStorageLocationMode_PrimaryOnly {
            get {
                return ResourceManager.GetString("AzureStorageLocationMode_PrimaryOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary, then secondary.
        /// </summary>
        internal static string AzureStorageLocationMode_PrimaryThenSecondary {
            get {
                return ResourceManager.GetString("AzureStorageLocationMode_PrimaryThenSecondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary only.
        /// </summary>
        internal static string AzureStorageLocationMode_SecondaryOnly {
            get {
                return ResourceManager.GetString("AzureStorageLocationMode_SecondaryOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary, then primary.
        /// </summary>
        internal static string AzureStorageLocationMode_SecondaryThenPrimary {
            get {
                return ResourceManager.GetString("AzureStorageLocationMode_SecondaryThenPrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Connection.
        /// </summary>
        internal static string TestConnectionResultTitle {
            get {
                return ResourceManager.GetString("TestConnectionResultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully connected to Azure Table storage.
        /// </summary>
        internal static string TestConnectionSuccessMessage {
            get {
                return ResourceManager.GetString("TestConnectionSuccessMessage", resourceCulture);
            }
        }
    }
}
