//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.DataTransfer.DocumentDb.UnitTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.DataTransfer.DocumentDb.UnitTests.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional parameters present in connection string.
        /// </summary>
        internal static string AdditionalParametersInConnectionString {
            get {
                return ResourceManager.GetString("AdditionalParametersInConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some documents were created when upsert was requested.
        /// </summary>
        internal static string AllDocumentShouldBeUpserted {
            get {
                return ResourceManager.GetString("AllDocumentShouldBeUpserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk sink adpater did not remove all created stored procedures.
        /// </summary>
        internal static string BulkSinkAdapterDidNotCleanup {
            get {
                return ResourceManager.GetString("BulkSinkAdapterDidNotCleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents collection was not created.
        /// </summary>
        internal static string CollectionWasNotCreated {
            get {
                return ResourceManager.GetString("CollectionWasNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid account endpoint was appended to the connection string.
        /// </summary>
        internal static string InvalidAccountEndpointInConnectionString {
            get {
                return ResourceManager.GetString("InvalidAccountEndpointInConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid account endpoint was parsed from the connection string.
        /// </summary>
        internal static string InvalidAccountEndpointParsedFromConnectionString {
            get {
                return ResourceManager.GetString("InvalidAccountEndpointParsedFromConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid account key was appended to the connection string.
        /// </summary>
        internal static string InvalidAccountKeyInConnectionString {
            get {
                return ResourceManager.GetString("InvalidAccountKeyInConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid account key was parsed from the connection string.
        /// </summary>
        internal static string InvalidAccountKeyParsedFromConnectionString {
            get {
                return ResourceManager.GetString("InvalidAccountKeyParsedFromConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capped enumerable was not properly serialized.
        /// </summary>
        internal static string InvalidCappedEnumerableSerialization {
            get {
                return ResourceManager.GetString("InvalidCappedEnumerableSerialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid database name was appended to the connection string.
        /// </summary>
        internal static string InvalidDatabaseNameInConnectionString {
            get {
                return ResourceManager.GetString("InvalidDatabaseNameInConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid database name was parsed from the connection string.
        /// </summary>
        internal static string InvalidDatabaseNameParsedFromConnectionString {
            get {
                return ResourceManager.GetString("InvalidDatabaseNameParsedFromConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data items were transferred.
        /// </summary>
        internal static string InvalidDataItemsTransferred {
            get {
                return ResourceManager.GetString("InvalidDataItemsTransferred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data item has invalid field names.
        /// </summary>
        internal static string InvalidFieldNames {
            get {
                return ResourceManager.GetString("InvalidFieldNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data item has invalid field value.
        /// </summary>
        internal static string InvalidFieldValue {
            get {
                return ResourceManager.GetString("InvalidFieldValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field names collection returned by filtered data item is invalid.
        /// </summary>
        internal static string InvalidFilteredFieldNames {
            get {
                return ResourceManager.GetString("InvalidFilteredFieldNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field value returned by filtered data item is invalid.
        /// </summary>
        internal static string InvalidFilteredFieldValue {
            get {
                return ResourceManager.GetString("InvalidFilteredFieldValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number of data items was transfered.
        /// </summary>
        internal static string InvalidNumberOfDataItemsTransferred {
            get {
                return ResourceManager.GetString("InvalidNumberOfDataItemsTransferred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field names collection returned by remapped data item is invalid.
        /// </summary>
        internal static string InvalidRemappedFieldNames {
            get {
                return ResourceManager.GetString("InvalidRemappedFieldNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field value returned by remapped data item is invalid.
        /// </summary>
        internal static string InvalidRemappedFieldValue {
            get {
                return ResourceManager.GetString("InvalidRemappedFieldValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect substitutions applied by the pattern resolver.
        /// </summary>
        internal static string InvalidSubstitutionsApplied {
            get {
                return ResourceManager.GetString("InvalidSubstitutionsApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluated Javascript expression returned invalid value.
        /// </summary>
        internal static string InvalidValueFromEvaluatedExpression {
            get {
                return ResourceManager.GetString("InvalidValueFromEvaluatedExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty collection link passed to CreateDocumentAsync of DocumentDB client.
        /// </summary>
        internal static string MissingCollectionLinkInCreateDocumentAsync {
            get {
                return ResourceManager.GetString("MissingCollectionLinkInCreateDocumentAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty collection link passed to UpsertDocumentAsync of DocumentDB client.
        /// </summary>
        internal static string MissingCollectionLinkInUpsertDocumentAsync {
            get {
                return ResourceManager.GetString("MissingCollectionLinkInUpsertDocumentAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No collection name passed to GetOrCreateCollectionAsync of DocumentDB client.
        /// </summary>
        internal static string MissingCollectionNameInGetOrCreateCollection {
            get {
                return ResourceManager.GetString("MissingCollectionNameInGetOrCreateCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No database name passed to GetOrCreateCollectionAsync of DocumentDB client.
        /// </summary>
        internal static string MissingDatabaseNameInGetOrCreateCollection {
            get {
                return ResourceManager.GetString("MissingDatabaseNameInGetOrCreateCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document passed to CreateDocumentAsync of DocumentDB client is null.
        /// </summary>
        internal static string MissingDocumentInCreateDocumentAsync {
            get {
                return ResourceManager.GetString("MissingDocumentInCreateDocumentAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document passed to UpsertDocumentAsync of DocumentDB client is null.
        /// </summary>
        internal static string MissingDocumentInUpsertDocumentAsync {
            get {
                return ResourceManager.GetString("MissingDocumentInUpsertDocumentAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some documents were upserted when create only was requested.
        /// </summary>
        internal static string NoDocumentsShouldBeUpserted {
            get {
                return ResourceManager.GetString("NoDocumentsShouldBeUpserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection of field names returned from filtered data item is null.
        /// </summary>
        internal static string NullFilteredFieldNames {
            get {
                return ResourceManager.GetString("NullFilteredFieldNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nested data item is null.
        /// </summary>
        internal static string NullNestedDataItem {
            get {
                return ResourceManager.GetString("NullNestedDataItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection of field names returned from remapped data item is null.
        /// </summary>
        internal static string NullRemappedFieldNames {
            get {
                return ResourceManager.GetString("NullRemappedFieldNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parallel sink adapter is not expected to create a stored procedure.
        /// </summary>
        internal static string ParallelSinkAdapterCreatedStoredProcedure {
            get {
                return ResourceManager.GetString("ParallelSinkAdapterCreatedStoredProcedure", resourceCulture);
            }
        }
    }
}
