//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.DataTransfer.DocumentDb {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.DataTransfer.DocumentDb.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocumentDB account end-point URL should be provided as part of the connection string.
        /// </summary>
        internal static string AccountEndpointMissing {
            get {
                return ResourceManager.GetString("AccountEndpointMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocumentDB account key should be provided as part of the connection string.
        /// </summary>
        internal static string AccountKeyMissing {
            get {
                return ResourceManager.GetString("AccountKeyMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both Query and QueryFile cannot be set at the same time.
        /// </summary>
        internal static string AmbiguousQuery {
            get {
                return ResourceManager.GetString("AmbiguousQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to buffer an item, slot is already occupied.
        /// </summary>
        internal static string BufferSlotIsOccupied {
            get {
                return ResourceManager.GetString("BufferSlotIsOccupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploads data into DocumentDB collection in batches.
        /// </summary>
        internal static string BulkSinkDescription {
            get {
                return ResourceManager.GetString("BulkSinkDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents collection name is required.
        /// </summary>
        internal static string CollectionNameMissing {
            get {
                return ResourceManager.GetString("CollectionNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocumentDB connection string is required.
        /// </summary>
        internal static string ConnectionStringMissing {
            get {
                return ResourceManager.GetString("ConnectionStringMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dt-{0}-{1}-{2}.
        /// </summary>
        internal static string CustomUserAgentSuffixFormat {
            get {
                return ResourceManager.GetString("CustomUserAgentSuffixFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents database name should be provided as part of the connection string.
        /// </summary>
        internal static string DatabaseNameMissing {
            get {
                return ResourceManager.GetString("DatabaseNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data item already contains field &quot;{0}&quot;.
        /// </summary>
        internal static string DataItemAlreadyContainsField {
            get {
                return ResourceManager.GetString("DataItemAlreadyContainsField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document cannot be indexed in bulk because it exceeds specified script size limit.
        /// </summary>
        internal static string DocumentSizeExceedsBulkScriptSize {
            get {
                return ResourceManager.GetString("DocumentSizeExceedsBulkScriptSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create documents collection &quot;{0}&quot;.
        /// </summary>
        internal static string FailedToCreateCollectionFormat {
            get {
                return ResourceManager.GetString("FailedToCreateCollectionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create documents database &quot;{0}&quot;.
        /// </summary>
        internal static string FailedToCreateDatabaseFormat {
            get {
                return ResourceManager.GetString("FailedToCreateDatabaseFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create document: {0}.
        /// </summary>
        internal static string FailedToCreateDocumentFormat {
            get {
                return ResourceManager.GetString("FailedToCreateDocumentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create stored procedure &quot;{0}&quot;.
        /// </summary>
        internal static string FailedToCreateStoredProcedureFormat {
            get {
                return ResourceManager.GetString("FailedToCreateStoredProcedureFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch size should be greater than zero.
        /// </summary>
        internal static string InvalidBatchSize {
            get {
                return ResourceManager.GetString("InvalidBatchSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max script size should be greater than zero.
        /// </summary>
        internal static string InvalidMaxScriptSize {
            get {
                return ResourceManager.GetString("InvalidMaxScriptSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of parallel requests should be greater than zero.
        /// </summary>
        internal static string InvalidNumberOfParallelRequests {
            get {
                return ResourceManager.GetString("InvalidNumberOfParallelRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of retries should be greater than zero.
        /// </summary>
        internal static string InvalidNumberOfRetries {
            get {
                return ResourceManager.GetString("InvalidNumberOfRetries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry interval cannot be negative.
        /// </summary>
        internal static string InvalidRetryInterval {
            get {
                return ResourceManager.GetString("InvalidRetryInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploads data into DocumentDB collection.
        /// </summary>
        internal static string ParallelSinkDescription {
            get {
                return ResourceManager.GetString("ParallelSinkDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocumentDB sink adapter should be initialized before it can be used.
        /// </summary>
        internal static string SinkIsNotInitialized {
            get {
                return ResourceManager.GetString("SinkIsNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reads data from DocumentDB collection.
        /// </summary>
        internal static string SourceDescription {
            get {
                return ResourceManager.GetString("SourceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocumentDB source adapter should be initialized before it can be used.
        /// </summary>
        internal static string SourceIsNotInitialized {
            get {
                return ResourceManager.GetString("SourceIsNotInitialized", resourceCulture);
            }
        }
    }
}
