//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.DataTransfer.ConsoleHost.UnitTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.DataTransfer.ConsoleHost.UnitTests.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option &apos;{0}&apos; was not returned by the configuration fatory.
        /// </summary>
        internal static string ConfigurationOptionMissingFormat {
            get {
                return ResourceManager.GetString("ConfigurationOptionMissingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid configuration option description returned for property &apos;{0}&apos;.
        /// </summary>
        internal static string InvalidConfigurationOptionDescriptionFormat {
            get {
                return ResourceManager.GetString("InvalidConfigurationOptionDescriptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid infrastructure configuration parsed from string arguments.
        /// </summary>
        internal static string InvalidInfrastructureConfigurationParsed {
            get {
                return ResourceManager.GetString("InvalidInfrastructureConfigurationParsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number of options returned by the configuration factory.
        /// </summary>
        internal static string InvalidNumberOfOptions {
            get {
                return ResourceManager.GetString("InvalidNumberOfOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vlue of the proxy property &apos;{0}&apos; is invalid.
        /// </summary>
        internal static string InvalidProxyPropertyValueFormat {
            get {
                return ResourceManager.GetString("InvalidProxyPropertyValueFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated proxy type is not valid.
        /// </summary>
        internal static string InvalidProxyType {
            get {
                return ResourceManager.GetString("InvalidProxyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid source configuration parsed from string arguments.
        /// </summary>
        internal static string InvalidSourceConfigurationParsed {
            get {
                return ResourceManager.GetString("InvalidSourceConfigurationParsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid source name parsed from string arguments.
        /// </summary>
        internal static string InvalidSourceNameParsed {
            get {
                return ResourceManager.GetString("InvalidSourceNameParsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid target configuration parsed from string arguments.
        /// </summary>
        internal static string InvalidTargetConfigurationParsed {
            get {
                return ResourceManager.GetString("InvalidTargetConfigurationParsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid target name parsed from string arguments.
        /// </summary>
        internal static string InvalidTargetNameParsed {
            get {
                return ResourceManager.GetString("InvalidTargetNameParsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options collection returned by configuration factory is null.
        /// </summary>
        internal static string NullOptionsReturned {
            get {
                return ResourceManager.GetString("NullOptionsReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic proxy instance is null.
        /// </summary>
        internal static string NullProxyGenerated {
            get {
                return ResourceManager.GetString("NullProxyGenerated", resourceCulture);
            }
        }
    }
}
